---

sudo: required
language: python
services:
  - docker

matrix:
  fast_finish: true
  include:
    - env: distro=debian version=9 tags="9 stretch latest"
    - env: distro=debian version=8 tags="8 jessie"
    - env: distro=centos version=7 tags="7 latest"
    - env: distro=centos version=6 tags="6"
    - env: distro=ubuntu version=bionic tags="18.04 bionic latest"
  allow_failures:
    - env: distro=ubuntu version=bionic tags="18.04 bionic latest"

install:
  - git clone --branch develop https://github.com/ansible/ansible-container.git && pip install -e ansible-container[docker]
  - pip install -r pip-requirements.txt

script:
  - | 
    ansible localhost -m template \
                      -a "src=container.yml.j2 dest=container.yml" \
                      -e "{ "distro": "${distro}", "version": "${version}", "command": "/sbin/init" }"
  - ansible-container build -- -v

deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: never
